package baseUrls;

import assignments.RestAssuredAssign13.CreateContact;
import io.restassured.builder.RequestSpecBuilder;
import io.restassured.http.ContentType;
import io.restassured.specification.RequestSpecification;
import org.testng.annotations.BeforeMethod;

public class DocumenterContactBaseUrl {

    protected RequestSpecification spec;
    @BeforeMethod
    public void baseSetUp(){

        String Token = CreateContact.Token;
        spec = new RequestSpecBuilder()

                .setBaseUri("https://thinking-tester-contact-list.herokuapp.com")
                .addHeader("Authorization", "Bearer " + Token)
                .setContentType(ContentType.JSON)
                .build();


        /* Bearer Authentication:
        An HTTP authentication scheme which uses an encrypted string as a token to
        access the restricted resources. This token is usually generated by the server when a login request
        is made by the client. It would be as below.

         */

    }
}
